#-----------------------
#Title: Chapter 1 tasks
#Page: 12
#Date: 02/05/25
#-----------------------

print("Goodbye ", end="")
print("Goodbye")
print()

print("No\t way\t", end=".")
print()

print("\n /------\  ")
print("|  @  @  |")
print("|   ^    |")
print("|   \/   |")
print(" \------/  ")
print()

print("*     *")
print(" *   * ")
print("   *   ")
print(" *   * ")
print("*     *")
print()

print("     *")
print("   *   *")
print(" *       *")
print("***********")
print()

print("    *** ")
print("  *     *")
print("*         *")
print("*         *")
print("*         *")
print("  *     *")
print("    *** ")
print()

print("       *****")
print("     *       *")
print("   *           *")
print(" *               *")
print(" *               *")
print(" *               *")
print("   *           *")
print("     *       *")
print("       *****")
print()

print("\t*     *")
print("\t *   * ")
print("\t   *   ")
print("\t *   * ")
print("\t*     *")

print("*     *", end=" ")
print("*     *", end=" ")
print("*     *")
print(" *   * ", end=" ")
print(" *   * ", end=" ")
print(" *   * ")
print("   *   ", end=" ")
print("   *   ", end=" ")
print("   *   ")
print(" *   * ", end=" ")
print(" *   * ", end=" ")
print(" *   * ")
print("*     *", end=" ")
print("*     *", end=" ")
print("*     *")

print("\t*     *")
print("\t *   * ")
print("\t   *   ")
print("\t *   * ")
print("\t*     *")
print()

print("\tx     x")
print("\t x   x ")
print("\t   x   ")
print("\t x   x ")
print("\tx     x")

print("x     x x     x x     x")
print(" x   x   x   x   x   x ")
print("   x       x       x   ")
print(" x   x   x   x   x   x ")
print("x     x x     x x     x")

print("\tx     x")
print("\t x   x ")
print("\t   x   ")
print("\t x   x ")
print("\tx     x")
print()
